// Code generated by addchain. Do not edit.

use crate::fields::FieldElement;

/// Exponentiates a field element to a constant power.
#[allow(unused_mut)]
pub(crate) fn exp<F: FieldElement>(x: F) -> F {
    // This is implemented with addition chain exponentiation, using the following chain:
    //
    //   _10       = 2*1
    //   _11       = 1 + _10
    //   _1100     = _11 << 2
    //   _1111     = _11 + _1100
    //   _11110000 = _1111 << 4
    //   _11111111 = _1111 + _11110000
    //   x16       = _11111111 << 8 + _11111111
    //   x32       = x16 << 16 + x16
    //   x64       = x32 << 32 + x32
    //   x65       = 2*x64 + 1
    //   x129      = x65 << 64 + x64
    //   x130      = 2*x129 + 1
    //   x259      = x130 << 129 + x129
    //   x260      = 2*x259 + 1
    //   x519      = x260 << 259 + x259
    //   return      x519 << 2 + 1
    //
    // Operations: 520 squares and 13 multiplications.
    //
    // Generated by github.com/mmcloughlin/addchain v0.4.0.

    let mut t0;
    let mut t1;
    let mut z;

    // Step 1: t0 = x^0x2
    t0 = x.square();

    // Step 2: t0 = x^0x3
    t0 = x * t0;

    // Step 4: t1 = x^0xc
    t1 = t0.square();
    for _ in 1..2 {
        t1 = t1.square();
    }

    // Step 5: t0 = x^0xf
    t0 *= t1;

    // Step 9: t1 = x^0xf0
    t1 = t0.square();
    for _ in 1..4 {
        t1 = t1.square();
    }

    // Step 10: t0 = x^0xff
    t0 *= t1;

    // Step 18: t1 = x^0xff00
    t1 = t0.square();
    for _ in 1..8 {
        t1 = t1.square();
    }

    // Step 19: t0 = x^0xffff
    t0 *= t1;

    // Step 35: t1 = x^0xffff0000
    t1 = t0.square();
    for _ in 1..16 {
        t1 = t1.square();
    }

    // Step 36: t0 = x^0xffffffff
    t0 *= t1;

    // Step 68: t1 = x^0xffffffff00000000
    t1 = t0.square();
    for _ in 1..32 {
        t1 = t1.square();
    }

    // Step 69: t0 = x^0xffffffffffffffff
    t0 *= t1;

    // Step 70: t1 = x^0x1fffffffffffffffe
    t1 = t0.square();

    // Step 71: t1 = x^0x1ffffffffffffffff
    t1 = x * t1;

    // Step 135: t1 = x^0x1ffffffffffffffff0000000000000000
    for _ in 0..64 {
        t1 = t1.square();
    }

    // Step 136: t0 = x^0x1ffffffffffffffffffffffffffffffff
    t0 *= t1;

    // Step 137: t1 = x^0x3fffffffffffffffffffffffffffffffe
    t1 = t0.square();

    // Step 138: t1 = x^0x3ffffffffffffffffffffffffffffffff
    t1 = x * t1;

    // Step 267: t1 = x^0x7fffffffffffffffffffffffffffffffe00000000000000000000000000000000
    for _ in 0..129 {
        t1 = t1.square();
    }

    // Step 268: t0 = x^0x7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    t0 *= t1;

    // Step 269: t1 = x^0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe
    t1 = t0.square();

    // Step 270: t1 = x^0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    t1 = x * t1;

    // Step 529: t1 = x^0x7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff80000000000000000000000000000000000000000000000000000000000000000
    for _ in 0..259 {
        t1 = t1.square();
    }

    // Step 530: t0 = x^0x7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    t0 *= t1;

    // Step 532: t0 = x^0x1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc
    for _ in 0..2 {
        t0 = t0.square();
    }

    // Step 533: z = x^0x1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffd
    z = x * t0;

    z
}
